config/routes.rb
Rails.application.routes.draw do
  get 'hero/hero'
  #root "home/index"
  root 'home#index'
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'home/team'
  get 'home/index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :common, :only => [:index, :team]
  
  def common
    @hero_name = Faker::Superhero.name
    @hero_power = Faker::Superhero.power
    @corp_title = Faker::Job.title
    @corp_power = Faker::Company.bs
    @corp_power = @corp_power.titleize
    @rand_num = rand(1..1000)
    @barcode = Faker::Barcode.isbn 
    
    @avatar = Faker::Avatar.image(slug: @rand_num, size: "300x300", format: "png", set: "set1", bgset: "bg1")
  end

  def index
  end

  def team
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hero_helper.rb
module HeroHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Superhero Name Generator", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About Us", root_path %></li>
        <li><%= link_to "Contact Us", root_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home Page", home_index_path %></li>
        <li><%= link_to "Create A Superhero", home_team_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to "Click Here to Generate a New Superhero", root_path %></h3>
  </div>
  <div class="panel-body">

 
  

  <div class="row">
    <div class="col-md-4">
    <%= image_tag @avatar %>
    </div>
    <div class="col-md-4">
      <h3>Your Superhero Name: </h3><br/>
      <h4><span class="red"><%= @hero_name %></span></h4> </br>
      <h3>Your Superhero Power:</h3>  <br/>
      <h4><span class="red"><%= @hero_power %></span></h4> <br/><br/>
      <br/><br/>
      <h3>Your Undercover Day Job is:</h3> <br/>
      <h4><span class="red"><%= @corp_title.titleize %></span> </h4><br/>
      <h3>Your Corporate Superpower is:</h3> <br/>
      <h4><span class="red"><%= @corp_power.titleize %></span> </h4><br/>
    </div>
    <div>
    <h3>Superhero #: </h3><br/>
    <h4><span class="red"><%= @barcode %>% </h4></span>
    </div>
  </div>
    <br/>

<div class="panel-footer"><%= link_to "Create a Whole Superhero Team", home_team_path %></div>
</div>

app/views/home/team.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to "Click Here to Generate a New Superhero", root_path %></h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
<div class="panel-footer"><%= link_to "Create a Whole Superhero Team", home_team_path %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superhero Name Generator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'home/navbar' %>
  <div class="container-fluid">
    <%= yield %>
  </div>
  <br/>
  <br/>
  <br/>
  <center>Copyright © superheros.com - All Rights Reserved</center>
  </body>
</html>